### ISSUE TITLE
Host header option missing.

### ISSUE THREAD

**Issue by andreiLita** [barbarbar338/node-ngrok-cli#1]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `node-ngrok-cli@0.0.2` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/node-ngrok-cli/dist/index.js b/node_modules/node-ngrok-cli/dist/index.js
index bea5335..76d68e5 100644
--- a/node_modules/node-ngrok-cli/dist/index.js
+++ b/node_modules/node-ngrok-cli/dist/index.js
@@ -111,6 +111,12 @@ daph_1.default.createCommand({
             default: false,
             isOptional: true,
         },
+        {
+            name: "host_header",
+            type: String,
+            default: false,
+            isOptional: true,
+        },
     ],
 }, (_command, args) => __awaiter(void 0, void 0, void 0, function* () {
     pogger.event("Starting NGROK tunnel");
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by barbarbar338** [comment]
Thanks for the catch! I'll publish a new version in a few minutes.

**Comment by barbarbar338** [comment]
Well I'm looking at source code and can'T find anything related to header or host_header. Are you sure that this is a thing?
